name: Push to fork
on:
  push:
    branches: 
      - 'fork-*'
    types: [closed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{toJSON(github)}}"
      - name: Make a comment with a secret
        run: |
          echo "Github ref ${{github.event.ref}}"
          ref=${{github.event.ref}}
          gh pr comment ${ref##*fork-} --body "PR comment from push event" -R ${{github.repository}}
        env:
          GITHUB_TOKEN: ${{secrets.GA_PAT }}