name: Labeled Events
on:
  pull_request_target:
    branches: 
      - '**fork-*'
    types: [closed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{toJSON(github)}}"
      - name: Make a comment with a secret
        run: |
          gh pr comment ${{github.event.number}} --body "PR comment from closed pr event" -R ${{github.repository}}
        env:
          GITHUB_TOKEN: ${{secrets.GA_PAT }}