name: Upload to PYPI on merge
on:
  pull_request:
    types: [closed]
env:
  INTERNAL_REPO: NCR-Corporation/gsre-internal
  TESTPYPI_UPLOADED: testpypi-uploaded
jobs:
  # wf level env vars are not accessible to job level if conditions but outputs of jobs in needs are
  env-vars:
    runs-on: ubuntu-latest
    outputs:
      testpypi_uploaded: ${{env.TESTPYPI_UPLOADED}}
    steps:
      - run: echo "${{toJSON(github)}}"
  upload:
    name: Upload to Pypi server
    needs: [env-vars]
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, needs.outputs.env-vars.testpypi_uploaded)
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Upload
        run: |
          echo "Upload to prod server"
          echo "${GITHUB_REF#refs/heads/}"
          gh workflow run pypi_upload.yml -R $INTERNAL_REPO -f repo=${{github.repository}} -f branch=${GITHUB_REF#refs/heads/} -f pr_num=${{github.event.number}} -f pypi_server='prod'
        env:
          GITHUB_TOKEN: ${{secrets.GA_PAT }}
